name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: Multirun Command
        run: |
          node -v
          npm -v
  pararell-job-macos:
    runs-on: macos-latest
    steps:
      - name: View SW Version
        run: sw_vers
  
  depandent-job:
      runs-on: window-latest
      needs: run-shell-commands
      steps:
        - name: echo the string
          run: Write-Output "Windows String"
        - name: Error Step
          run: doesnotexits

